---
- name: Install and configure dotfiles
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Checkout dotfiles to local directory
      ansible.builtin.git:
        repo: 'https://github.com/adrielp/dotfiles.git'
        dest: '~/adrielp-dotfiles'
        version: master

    - name: Ensure config and autoload exist
      ansible.builtin.file:
        path: ~/.config/nvim/autoload
        state: directory

    - name: Check if .tmux.conf exists
      ansible.builtin.stat:
        path: ~/.tmux.conf
      register: stat_tmux_conf

    - name: Backup old .tmux.conf if exists
      ansible.builtin.shell: |
        mv ~/.tmux.conf ~/bak.ap.tmux.conf
      when: stat_tmux_conf.stat.exists

    - name: Copy .tmux.conf from repo to home
      ansible.builtin.shell: |
        cp ~/adrielp-dotfiles/.tmux.conf ~/.tmux.conf

    - name: Check if ZSH is installed in /usr/local/bin
      ansible.builtin.stat:
        path: /usr/local/bin/zsh
      register: stat_zsh

    - name: Check if .zshrc exists if ZSH installed
      ansible.builtin.stat:
        path: ~/.zshrc
      register: stat_zshrc
      #when: stat_zsh.stat.exists

    - name: Backup old .zshrc if exists
      ansible.builtin.shell: |
        mv ~/.zshrc ~/bak.ap.zshrc
      when: stat_zshrc.stat.exists

    - name: Copy .zshrc into home directory if ZSH exists
      ansible.builtin.shell: |
        cp ~/adrielp-dotfiles/.zshrc ~/.zshrc
      when: stat_zshrc.stat.exists

    - name: Check if init.vim exists
      ansible.builtin.stat:
        path: ~/.config/nvim/init.vim
      register: stat_init_vim

    - name: Backup old init.vim if exists
      ansible.builtin.shell: |
        mv ~/.config/nvim/init.vim \
          ~/.config/nvim/bak.ap.init.vim
      when: stat_init_vim.stat.exists

    - name: Copy init.vim to .config/nvim/init.vim
      ansible.builtin.shell: |
        cp ~/adrielp-dotfiles/.config/nvim/init.vim \
          ~/.config/nvim/init.vim

    - name: Install Powerlevel 10k
      ansible.builtin.shell: |
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
          ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
      ignore_errors: true

    - name: Install Autosuggestions
      ansible.builtin.shell: |
        git clone https://github.com/zsh-users/zsh-autosuggestions \
          ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
      ignore_errors: true

